config/routes.rb
Rails.application.routes.draw do
  resources :wines, only: %i[index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "wines#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

  def index
    url = Rails.application.config_for(:local_env)['api-url']
    if params[:query].present?
      params[:query].each do |country|
        url += "&country_codes%5B%5D=#{country}"
      end
    end
    
    result = RestClient.get url
    @wines = JSON.parse(result.body, symbolize_names: true)[:matches]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wines_helper.rb
module WinesHelper
  def country_code(wine)
    wine[:vintage][:wine][:region][:country]
  end

  def country_image_url(wine)
    "#{Rails.application.config_for(:local_env)['assets-url']}/countryFlags/#{country_code(wine).upcase}-48.png"
  end

  def ratings_average(wine)
    wine[:vintage][:wine][:statistics][:ratings_average]
  end

  def star_red_counter(wine)
    ratings_average(wine).floor
  end

  def star_blank_counter(wine)
    (5 - star_red_counter(wine))
  end

  def countries_for_filtering
    [['Argentina', 'ar'], ['Australia', 'au'], ['Austria', 'at'], ['Chile', 'cl'], ['France', 'fr'], ['Germany', 'de'], ['Italy', 'it'], ['Portugal', 'pt'], ['South Africa', 'za'], ['Spain', 'es'], ['United States', 'us']]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/wines/_wine.html.erb
<div class="row wine">
  <div class="col-sm-2">
    <%= image_tag("https://#{wine[:vintage][:image][:variations][:bottle_medium]}", class: "image-wrapper") %>
  </div>

  <div class="col-sm-10">
    <div class="winery-name-font-size"><%= wine[:vintage][:wine][:winery][:name] %></div>

    <div class="row">
      <div class="col-sm-8">
        <div class="winery-font mb-2">
          <%= "#{wine[:vintage][:wine][:name]} #{wine[:vintage][:year]}" %>
        </div>

        <div>
          <%= image_tag(country_image_url(wine), class: "image-country") %>
          <%= "#{wine[:vintage][:wine][:region][:name]}, #{IsoCountryCodes.find(country_code(wine)).name}" %>
        </div>
      </div>

      <div class="col-sm-4 text-center">
        <div class="rating"><%= ratings_average(wine) %></div>
        <%- star_red_counter(wine).times do %>
          <%= image_tag("#{Rails.application.config_for(:local_env)['assets-url']}/rating/star_10.svg", class: "rating-star star-red") %>
        <%- end %>

        <%- star_blank_counter(wine).times do %>
          <%= image_tag("#{Rails.application.config_for(:local_env)['assets-url']}/rating/star_0.svg", class: "rating-star star-blank") %>
        <%- end %>

        <div>
          <%= pluralize(wine[:vintage][:wine][:statistics][:ratings_count], 'rating') %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wines/index.html.erb
<div data-controller="wines">
  <h1 class="mt-5">Here is a list of wines we are currently offer</h1>

  <%= form_with(url: wines_path, method: :get) do |form| %>
    <div id="query">
      <p>Search by country name</p>
      <%- countries_for_filtering.each do |country, code| %>
        <%- checked = params['query'].present? ? (params['query'].include? code) : false %>
        <%= form.check_box :query, { multiple: true, class: "btn-check", "data-action": "wines#refresh", checked: checked }, code, false %>
        <%= form.label :query, country, class: "btn btn-outline-danger", for: "query_#{code}" %>
      <% end %>

      <%= form.submit 'Search', class: "btn btn-primary", id: "query_submit" %>
    </div>
  <% end %>

  <div id="wines" class="mt-5">
    <% @wines.each do |wine| %>
      <div class="row">
        <div class="card mb-5">
          <div class="card-body">
            <%= render partial: 'wines/wine', locals: { wine: wine } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>